load("@pypi//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "plotter",
    srcs = ["plotter.py"],
    deps = [
        "//simulation/swarm/proto:plotting_config_py_proto",
        "//simulation/swarm/py:agent",
        "//utils/visualization:mpl_config",
        requirement("matplotlib"),
        requirement("numpy"),
    ],
)
