load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "agent_controller",
    srcs = ["agent_controller.cc"],
    hdrs = ["agent_controller.h"],
    deps = [
        "//simulation/swarm:agent",
        "//simulation/swarm/proto:transformation_cc_proto",
        "@eigen",
    ],
)

cc_library(
    name = "apn_controller",
    srcs = ["apn_controller.cc"],
    hdrs = ["apn_controller.h"],
    deps = [
        ":pn_controller",
        "//simulation/swarm:agent",
        "//simulation/swarm/proto:transformation_cc_proto",
        "@eigen",
    ],
)

cc_test(
    name = "apn_controller_test",
    srcs = ["apn_controller_test.cc"],
    deps = [
        ":apn_controller",
        "//simulation/swarm:agent",
        "//simulation/swarm/proto:state_cc_proto",
        "@eigen",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "mpc_controller",
    srcs = ["mpc_controller.cc"],
    hdrs = ["mpc_controller.h"],
    deps = [
        ":agent_controller",
        "//base:commandlineflags",
        "//base:logging",
        "//simulation/swarm:agent",
        "//simulation/swarm/controls:mpc_controller",
        "//simulation/swarm/proto:transformation_cc_proto",
        "//simulation/swarm/utils:constants",
        "@eigen",
        "@libmpc",
    ],
)

cc_library(
    name = "pn_controller",
    srcs = ["pn_controller.cc"],
    hdrs = ["pn_controller.h"],
    deps = [
        ":agent_controller",
        "//simulation/swarm:agent",
        "//simulation/swarm/proto:transformation_cc_proto",
    ],
)

cc_test(
    name = "pn_controller_test",
    srcs = ["pn_controller_test.cc"],
    deps = [
        ":pn_controller",
        "//simulation/swarm:agent",
        "//simulation/swarm/proto:state_cc_proto",
        "@eigen",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
