module(name = "micromissiles")

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

bazel_dep(
    name = "abseil-cpp",
    version = "20260817.0",
)
bazel_dep(
    name = "eigen",
    version = "5.0.1",
)
bazel_dep(
    name = "googletest",
    version = "1.18.0",
)
bazel_dep(
    name = "pico-sdk",
    version = "2.3.0",
)
bazel_dep(
    name = "platforms",
    version = "1.1.0",
)
bazel_dep(
    name = "protobuf",
    version = "36.1.bcr.1",
)
bazel_dep(
    name = "rules_cc",
    version = "0.2.22",
)
bazel_dep(
    name = "rules_foreign_cc",
    version = "0.15.1",
)
bazel_dep(
    name = "rules_pkg",
    version = "1.3.0",
)
bazel_dep(
    name = "rules_python",
    version = "2.3.2",
)
bazel_dep(
    name = "rules_shell",
    version = "0.8.0",
)

single_version_override(
    module_name = "pico-sdk",
    patch_strip = 1,
    patches = ["//third_party/pico_sdk:pico_sdk.patch"],
)

# Boost library.
BOOST_VERSION = "1.92.0"

http_archive(
    name = "boost",
    build_file = "//third_party/boost:boost.BUILD",
    sha256 = "c4a3b310ddd2472416e091067166b0713be97c63f38c212c484ada022fd296ce",
    strip_prefix = "boost_{}".format(BOOST_VERSION.replace(".", "_")),
    url = "https://archives.boost.io/release/{}/source/boost_{}.tar.gz".format(
        BOOST_VERSION,
        BOOST_VERSION.replace(".", "_"),
    ),
)

# libmpc++ library.
LIBMPC_VERSION = "1.0.0"

http_archive(
    name = "libmpc",
    build_file = "//third_party/libmpc:libmpc.BUILD",
    patch_args = ["-p1"],
    patches = ["//third_party/libmpc:libmpc.patch"],
    sha256 = "1445741e5bf62e0b0dd350d0d2fac4b61cdfc1a6737026d3d1b12787ac787094",
    strip_prefix = "libmpc-{}".format(LIBMPC_VERSION),
    url = "https://github.com/nicolapiccinelli/libmpc/archive/refs/tags/{}.tar.gz".format(LIBMPC_VERSION),
)

# NLopt library.
NLOPT_VERSION = "2.11.0"

http_archive(
    name = "nlopt",
    build_file = "//third_party/nlopt:nlopt.BUILD",
    sha256 = "53e552d83e9294d67db37f0f4a23f15933a9ef698485301a18b98b40004cf0de",
    strip_prefix = "nlopt-{}".format(NLOPT_VERSION),
    url = "https://github.com/stevengj/nlopt/archive/refs/tags/v{}.tar.gz".format(NLOPT_VERSION),
)

# OpenCV library.
OPENCV_VERSION = "5.0.0"

http_archive(
    name = "opencv",
    build_file = "//third_party/opencv:opencv.BUILD",
    sha256 = "b0528f5a1d379d59d4701cb28c36e22214cc51cf64594e5b56f2d3e6c0233095",
    strip_prefix = "opencv-{}".format(OPENCV_VERSION),
    url = "https://github.com/opencv/opencv/archive/refs/tags/{}.tar.gz".format(OPENCV_VERSION),
)

# OpenCV modules.
OPENCV_CONTRIB_VERSION = "5.0.0"

http_archive(
    name = "opencv_contrib",
    build_file = "//third_party/opencv_contrib:opencv_contrib.BUILD",
    patch_args = ["-p1"],
    patches = ["//third_party/opencv_contrib:opencv_contrib.patch"],
    sha256 = "c58f6344170c39abf187c56f3843b59cab1fd3e89cf19ba2ce25dc061659b27f",
    strip_prefix = "opencv_contrib-{}".format(OPENCV_CONTRIB_VERSION),
    url = "https://github.com/opencv/opencv_contrib/archive/refs/tags/{}.tar.gz".format(OPENCV_CONTRIB_VERSION),
)

# OSQP library.
OSQP_VERSION = "1.0.0"

http_archive(
    name = "osqp",
    build_file = "//third_party/osqp:osqp.BUILD",
    sha256 = "dd6a1c2e7e921485697d5e7cdeeb043c712526c395b3700601f51d472a7d8e48",
    strip_prefix = "osqp-{}".format(OSQP_VERSION),
    url = "https://github.com/osqp/osqp/archive/refs/tags/v{}.tar.gz".format(OSQP_VERSION),
)

# Configure Pico SDK toolchains.
register_toolchains(
    "@pico-sdk//bazel/toolchain:linux-x86_64-rp2040",
    "@pico-sdk//bazel/toolchain:linux-x86_64-rp2350",
    "@pico-sdk//bazel/toolchain:win-x86_64-rp2040",
    "@pico-sdk//bazel/toolchain:win-x86_64-rp2350",
    "@pico-sdk//bazel/toolchain:mac-x86_64-rp2040",
    "@pico-sdk//bazel/toolchain:mac-x86_64-rp2350",
    "@pico-sdk//bazel/toolchain:mac-aarch64-rp2040",
    "@pico-sdk//bazel/toolchain:mac-aarch64-rp2350",
)

# Configure the Python toolchain.
python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    is_default = True,
    python_version = "3.13",
)

# Load pip dependencies.
pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(
    hub_name = "pypi",
    python_version = "3.13",
    requirements_lock = "//deps:requirements.txt",
)
use_repo(pip, "pypi")
