module(name = "micromissiles")

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

bazel_dep(
    name = "abseil-cpp",
    version = "20250127.0",
)
bazel_dep(
    name = "eigen",
    version = "4.0.0-20241125.bcr.1",
)
bazel_dep(
    name = "googletest",
    version = "1.16.0",
)
bazel_dep(
    name = "pico-sdk",
    version = "2.1.1",
)
bazel_dep(
    name = "platforms",
    version = "0.0.11",
)
bazel_dep(
    name = "protobuf",
    version = "30.0",
)
bazel_dep(
    name = "rules_cc",
    version = "0.1.1",
)
bazel_dep(
    name = "rules_foreign_cc",
    version = "0.14.0",
)
bazel_dep(
    name = "rules_pkg",
    version = "1.0.1",
)
bazel_dep(
    name = "rules_python",
    version = "1.2.0",
)

# Pico SDK toolchains.
register_toolchains(
    "@pico-sdk//bazel/toolchain:linux-x86_64-rp2040",
    "@pico-sdk//bazel/toolchain:linux-x86_64-rp2350",
    "@pico-sdk//bazel/toolchain:win-x86_64-rp2040",
    "@pico-sdk//bazel/toolchain:win-x86_64-rp2350",
    "@pico-sdk//bazel/toolchain:mac-x86_64-rp2040",
    "@pico-sdk//bazel/toolchain:mac-x86_64-rp2350",
    "@pico-sdk//bazel/toolchain:mac-aarch64-rp2040",
    "@pico-sdk//bazel/toolchain:mac-aarch64-rp2350",
)

# Boost library.
BOOST_VERSION = "1.87.0"

http_archive(
    name = "boost",
    build_file = "//third_party/boost:boost.BUILD",
    sha256 = "f55c340aa49763b1925ccf02b2e83f35fdcf634c9d5164a2acb87540173c741d",
    strip_prefix = "boost_{}".format(BOOST_VERSION.replace(".", "_")),
    url = "https://archives.boost.io/release/{}/source/boost_{}.tar.gz".format(
        BOOST_VERSION,
        BOOST_VERSION.replace(".", "_"),
    ),
)

# libmpc++ library.
LIBMPC_VERSION = "0.7.0"

http_archive(
    name = "libmpc",
    build_file = "//third_party/libmpc:libmpc.BUILD",
    sha256 = "b1ab237345d6a39a5314e676af8353c6fb66663630a5cfda23eeb12f6f42614b",
    strip_prefix = "libmpc-{}".format(LIBMPC_VERSION),
    url = "https://github.com/nicolapiccinelli/libmpc/archive/refs/tags/{}.tar.gz".format(LIBMPC_VERSION),
)

# NLopt library.
NLOPT_VERSION = "2.9.1"

http_archive(
    name = "nlopt",
    build_file = "//third_party/nlopt:nlopt.BUILD",
    sha256 = "1e6c33f8cbdc4138d525f3326c231f14ed50d99345561e85285638c49b64ee93",
    strip_prefix = "nlopt-{}".format(NLOPT_VERSION),
    url = "https://github.com/stevengj/nlopt/archive/refs/tags/v{}.tar.gz".format(NLOPT_VERSION),
)

# OpenCV library.
OPENCV_VERSION = "4.11.0"

http_archive(
    name = "opencv",
    build_file = "//third_party/opencv:opencv.BUILD",
    sha256 = "9a7c11f924eff5f8d8070e297b322ee68b9227e003fd600d4b8122198091665f",
    strip_prefix = "opencv-{}".format(OPENCV_VERSION),
    url = "https://github.com/opencv/opencv/archive/refs/tags/{}.tar.gz".format(OPENCV_VERSION),
)

# OpenCV modules.
OPENCV_CONTRIB_VERSION = "4.11.0"

http_archive(
    name = "opencv_contrib",
    build_file = "//third_party/opencv_contrib:opencv_contrib.BUILD",
    sha256 = "2dfc5957201de2aa785064711125af6abb2e80a64e2dc246aca4119b19687041",
    strip_prefix = "opencv_contrib-{}".format(OPENCV_CONTRIB_VERSION),
    url = "https://github.com/opencv/opencv_contrib/archive/refs/tags/{}.tar.gz".format(OPENCV_CONTRIB_VERSION),
)

# OSQP library.
OSQP_COMMIT_HASH = "27a2d51fa9aea19e25a3b3f90b7026c5109b5bf5"

http_archive(
    name = "osqp",
    build_file = "//third_party/osqp:osqp.BUILD",
    sha256 = "478ec43bd4e7938cff175c34e3471895c4ad38605d44745f1a3f79e8278ba3bf",
    strip_prefix = "osqp-{}".format(OSQP_COMMIT_HASH),
    url = "https://github.com/osqp/osqp/archive/{}.tar.gz".format(OSQP_COMMIT_HASH),
)

# Configure the Python toolchain.
python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    is_default = True,
    python_version = "3.12",
)

# Load pip dependencies.
pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(
    hub_name = "pypi",
    python_version = "3.12",
    requirements_lock = "//deps:requirements.txt",
)
use_repo(pip, "pypi")
