load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:defs.bzl", "cc_binary")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "config",
    srcs = ["config.c"],
    hdrs = ["config.h"],
    target_compatible_with = select({
        "@pico-sdk//bazel/constraint:rp2040": [],
        "@pico-sdk//bazel/constraint:rp2350": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        ":dds",
        ":mixer",
        ":vco",
        ":vga",
        "@pico-sdk//src/rp2_common/hardware_spi",
    ],
)

cc_binary(
    name = "cw_main",
    srcs = ["cw_main.c"],
    target_compatible_with = select({
        "@pico-sdk//bazel/constraint:rp2040": [],
        "@pico-sdk//bazel/constraint:rp2350": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        ":config",
        ":dds",
        ":mixer",
        ":vco",
        ":vga",
        "@pico-sdk//src/rp2_common/pico_stdlib",
    ],
)

cc_library(
    name = "dds",
    srcs = ["dds.c"],
    hdrs = ["dds.h"],
    target_compatible_with = select({
        "@pico-sdk//bazel/constraint:rp2040": [],
        "@pico-sdk//bazel/constraint:rp2350": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        "//pico/common:spi",
        "@pico-sdk//src/common/pico_time",
        "@pico-sdk//src/rp2_common/hardware_gpio",
    ],
)

cc_binary(
    name = "fmcw_main",
    srcs = ["fmcw_main.c"],
    target_compatible_with = select({
        "@pico-sdk//bazel/constraint:rp2040": [],
        "@pico-sdk//bazel/constraint:rp2350": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        ":config",
        ":dds",
        ":mixer",
        ":vco",
        ":vga",
        "@pico-sdk//src/common/pico_time",
        "@pico-sdk//src/rp2_common/pico_stdlib",
    ],
)

cc_library(
    name = "mixer",
    srcs = ["mixer.c"],
    hdrs = ["mixer.h"],
    target_compatible_with = select({
        "@pico-sdk//bazel/constraint:rp2040": [],
        "@pico-sdk//bazel/constraint:rp2350": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = ["@pico-sdk//src/rp2_common/hardware_gpio"],
)

cc_library(
    name = "vco",
    srcs = ["vco.c"],
    hdrs = ["vco.h"],
    target_compatible_with = select({
        "@pico-sdk//bazel/constraint:rp2040": [],
        "@pico-sdk//bazel/constraint:rp2350": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        "//pico/common:spi",
        "@pico-sdk//src/rp2_common/hardware_gpio",
    ],
)

cc_library(
    name = "vga",
    srcs = ["vga.c"],
    hdrs = ["vga.h"],
    target_compatible_with = select({
        "@pico-sdk//bazel/constraint:rp2040": [],
        "@pico-sdk//bazel/constraint:rp2350": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = ["//pico/common:spi"],
)
