load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "spi",
    srcs = ["spi.c"],
    hdrs = ["spi.h"],
    target_compatible_with = select({
        "@pico-sdk//bazel/constraint:rp2040": [],
        "@pico-sdk//bazel/constraint:rp2350": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        "@pico-sdk//src/rp2_common/hardware_gpio",
        "@pico-sdk//src/rp2_common/hardware_spi",
    ],
)

cc_library(
    name = "led",
    srcs = ["led.c"],
    hdrs = ["led.h"],
    target_compatible_with = select({
        "@pico-sdk//bazel/constraint:rp2040": [],
        "@pico-sdk//bazel/constraint:rp2350": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        "@pico-sdk//src/rp2_common/hardware_gpio",
        "@pico-sdk//src/rp2_common/pico_stdlib",
    ],
)
