load("@pypi//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_binary", "py_library", "py_test")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "least_squares_trilaterator",
    srcs = ["least_squares_trilaterator.py"],
    deps = [
        ":trilaterator",
        "//utils:coordinates",
        requirement("numpy"),
    ],
)

py_test(
    name = "least_squares_trilaterator_test",
    srcs = ["least_squares_trilaterator_test.py"],
    deps = [
        ":least_squares_trilaterator",
        "//utils:coordinates",
        requirement("absl-py"),
        requirement("numpy"),
    ],
)

py_library(
    name = "nonlinear_least_squares_trilaterator",
    srcs = ["nonlinear_least_squares_trilaterator.py"],
    deps = [
        ":trilaterator",
        "//utils:coordinates",
        requirement("numpy"),
        requirement("scipy"),
    ],
)

py_test(
    name = "nonlinear_least_squares_trilaterator_test",
    srcs = ["nonlinear_least_squares_trilaterator_test.py"],
    deps = [
        ":nonlinear_least_squares_trilaterator",
        "//utils:coordinates",
        requirement("absl-py"),
        requirement("numpy"),
    ],
)

py_library(
    name = "trilaterator",
    srcs = ["trilaterator.py"],
    deps = [
        "//utils:coordinates",
        requirement("numpy"),
    ],
)

py_test(
    name = "trilaterator_test",
    srcs = ["trilaterator_test.py"],
    deps = [
        ":trilaterator",
        "//utils:coordinates",
        requirement("absl-py"),
        requirement("numpy"),
    ],
)

py_library(
    name = "trilaterator_factory",
    srcs = ["trilaterator_factory.py"],
    deps = [
        ":least_squares_trilaterator",
        ":nonlinear_least_squares_trilaterator",
        ":trilaterator",
        "//utils:coordinates",
        requirement("numpy"),
    ],
)

py_test(
    name = "trilaterator_factory_test",
    srcs = ["trilaterator_factory_test.py"],
    deps = [
        ":least_squares_trilaterator",
        ":nonlinear_least_squares_trilaterator",
        ":trilaterator_factory",
        "//utils:coordinates",
        requirement("absl-py"),
        requirement("numpy"),
    ],
)

py_binary(
    name = "trilaterator_monte_carlo_sensor_main",
    srcs = ["trilaterator_monte_carlo_sensor_main.py"],
    deps = [
        ":trilaterator_factory",
        "//utils:coordinates",
        "//utils/visualization:mpl_config",
        requirement("absl-py"),
        requirement("matplotlib"),
        requirement("numpy"),
    ],
)

py_binary(
    name = "trilaterator_monte_carlo_target_main",
    srcs = ["trilaterator_monte_carlo_target_main.py"],
    deps = [
        ":trilaterator_factory",
        "//utils:coordinates",
        "//utils/visualization:mpl_config",
        requirement("absl-py"),
        requirement("matplotlib"),
        requirement("numpy"),
    ],
)
