step_time: 0.01
missile_configs {
  initial_state {
    position {
      x: 0
      y: 0
      z: 100
    }
    velocity {
      x: 1
      y: 0
      z: 1000
    }
  }
}
missile_configs {
  initial_state {
    position {
      x: 0
      y: 0
      z: 120
    }
    velocity {
      x: 1
      y: 0
      z: 1000
    }
  }
}
missile_configs {
  initial_state {
    position {
      x: 0
      y: 10
      z: 100
    }
    velocity {
      x: 1
      y: 0
      z: 1000
    }
  }
}
missile_configs {
  initial_state {
    position {
      x: 0
      y: 10
      z: 120
    }
    velocity {
      x: 1
      y: 0
      z: 1000
    }
  }
}
target_configs {
  initial_state {
    position {
      x: 200000
      y: 0
      z: 40000
    }
    velocity {
      x: -1000
      y: 0
      z: 0
    }
  }
}
