step_time: 0.001
missile_configs {
  initial_state {
    position {
      x: 0
      y: 0
      z: 100
    }
    velocity {
      x: 1
      y: 0
      z: 1000
    }
  }
  physical_config {
    acceleration_config {
      max_reference_acceleration: 300
      reference_speed: 1000
    }
    lift_drag_config {
      lift_coefficient: 0.2
      drag_coefficient: 0.7
      lift_drag_ratio: 5
    }
    body_config {
      mass: 0.37
      cross_sectional_area: 3e-4
      fin_area: 6e-4
      body_area: 1e-2
    }
    sensor_config {
      frequency: 100
    }
    hit_config {
      hit_radius: 1
    }
  }
  plotting_config {
    color: BLUE
    linestyle: SOLID
    marker: TRIANGLE_UP
  }
}
missile_configs {
  initial_state {
    position {
      x: 0
      y: 0
      z: 120
    }
    velocity {
      x: 1
      y: 0
      z: 1000
    }
  }
  physical_config {
    acceleration_config {
      max_reference_acceleration: 300
      reference_speed: 1000
    }
    lift_drag_config {
      lift_coefficient: 0.2
      drag_coefficient: 0.7
      lift_drag_ratio: 5
    }
    body_config {
      mass: 0.37
      cross_sectional_area: 3e-4
      fin_area: 6e-4
      body_area: 1e-2
    }
    sensor_config {
      frequency: 100
    }
    hit_config {
      hit_radius: 1
    }
  }
  plotting_config {
    color: BLUE
    linestyle: SOLID
    marker: TRIANGLE_UP
  }
}
missile_configs {
  initial_state {
    position {
      x: 0
      y: 10
      z: 100
    }
    velocity {
      x: 1
      y: 0
      z: 1000
    }
  }
  physical_config {
    acceleration_config {
      max_reference_acceleration: 300
      reference_speed: 1000
    }
    lift_drag_config {
      lift_coefficient: 0.2
      drag_coefficient: 0.7
      lift_drag_ratio: 5
    }
    body_config {
      mass: 0.37
      cross_sectional_area: 3e-4
      fin_area: 6e-4
      body_area: 1e-2
    }
    sensor_config {
      frequency: 100
    }
    hit_config {
      hit_radius: 1
    }
  }
  plotting_config {
    color: BLUE
    linestyle: SOLID
    marker: TRIANGLE_UP
  }
}
missile_configs {
  initial_state {
    position {
      x: 0
      y: 10
      z: 120
    }
    velocity {
      x: 1
      y: 0
      z: 1000
    }
  }
  physical_config {
    acceleration_config {
      max_reference_acceleration: 300
      reference_speed: 1000
    }
    lift_drag_config {
      lift_coefficient: 0.2
      drag_coefficient: 0.7
      lift_drag_ratio: 5
    }
    body_config {
      mass: 0.37
      cross_sectional_area: 3e-4
      fin_area: 6e-4
      body_area: 1e-2
    }
    sensor_config {
      frequency: 100
    }
    hit_config {
      hit_radius: 1
    }
  }
  plotting_config {
    color: BLUE
    linestyle: SOLID
    marker: TRIANGLE_UP
  }
}
target_configs {
  initial_state {
    position {
      x: 200000
      y: 0
      z: 40000
    }
    velocity {
      x: -1000
      y: 0
      z: 0
    }
  }
  physical_config {
    hit_config {
      kill_probability: 0.6
    }
  }
  plotting_config {
    color: RED
    linestyle: SOLID
    marker: SQUARE
  }
}
