step_time: 0.001
missile_configs {
  initial_state {
    position {
      x: 0
      y: 0
      z: 100
    }
    velocity {
      x: 1
      y: 0
      z: 1000
    }
  }
}
missile_configs {
  initial_state {
    position {
      x: 0
      y: 0
      z: 120
    }
    velocity {
      x: 1
      y: 0
      z: 1000
    }
  }
}
missile_configs {
  initial_state {
    position {
      x: 0
      y: 10
      z: 100
    }
    velocity {
      x: 1
      y: 0
      z: 1000
    }
  }
}
missile_configs {
  initial_state {
    position {
      x: 0
      y: 10
      z: 120
    }
    velocity {
      x: 1
      y: 0
      z: 1000
    }
  }
}
target_configs {
  initial_state {
    position {
      x: 10000
      y: 0
      z: 150
    }
    velocity {
      x: -40
      y: -20
      z: 0
    }
  }
}
