missile_configs {
  initial_state {
    position {
      x: 0
      y: 0
      z: 100
    }
    velocity {
      x: 1
      y: 0
      z: 1000
    }
    acceleration {
      x: 0
      y: 0
      z: 0
    }
  }
}
target_configs {
  initial_state {
    position {
      x: 20000
      y: 0
      z: 150
    }
    velocity {
      x: -200
      y: 0
      z: 0
    }
    acceleration {
      x: 0
      y: 0
      z: 0
    }
  }
}
