load("@pypi//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_binary", "py_library")

package(default_visibility = ["//visibility:public"])

py_binary(
    name = "antenna_sweep_main",
    srcs = ["antenna_sweep_main.py"],
    deps = [
        ":fieldfox_interface",
        ":thorlabs_motor",
        requirement("absl-py"),
    ],
)

py_library(
    name = "fieldfox_interface",
    srcs = ["fieldfox_interface.py"],
)

py_library(
    name = "motor",
    srcs = ["motor.py"],
)

py_library(
    name = "polulu_tic_motor",
    srcs = ["polulu_tic_motor.py"],
    deps = [
        ":motor",
        requirement("absl-py"),
        requirement("pyyaml"),
    ],
)

py_binary(
    name = "polulu_tic_motor_move_main",
    srcs = ["polulu_tic_motor_move_main.py"],
    deps = [
        ":polulu_tic_motor",
        requirement("absl-py"),
    ],
)

py_library(
    name = "thorlabs_motor",
    srcs = ["thorlabs_motor.py"],
    deps = [
        ":motor",
        requirement("pylablib"),
    ],
)

py_binary(
    name = "thorlabs_motor_move_main",
    srcs = ["thorlabs_motor_move_main.py"],
    deps = [
        ":thorlabs_motor",
        requirement("absl-py"),
    ],
)
