step_time: 0.001
missile_configs {
  type: MICROMISSILE
  initial_state {
    position {
      x: 0
      y: 0
      z: 100
    }
    velocity {
      x: 1
      y: 0
      z: 1000
    }
  }
  dynamic_config {
    sensor_config {
      type: IDEAL
      frequency: 100
    }
    launch_config {
      launch_time: 0
    }
  }
  plotting_config {
    color: BLUE
    linestyle: SOLID
    marker: TRIANGLE_UP
  }
}
target_configs {
  type: MISSILE
  initial_state {
    position {
      x: 200000
      y: 0
      z: 40000
    }
    velocity {
      x: -1000
      y: 0
      z: 0
    }
  }
  plotting_config {
    color: RED
    linestyle: SOLID
    marker: SQUARE
  }
}
