load("@pypi//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_binary", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "constants",
    srcs = ["constants.py"],
)

py_library(
    name = "constraint",
    srcs = ["constraint.py"],
)

py_library(
    name = "design_variable",
    srcs = ["design_variable.py"],
)

py_library(
    name = "hfss_optimizer",
    srcs = ["hfss_optimizer.py"],
    deps = [
        ":design_variable",
        ":hfss_runner",
        ":s_parameter_constraint",
        requirement("absl-py"),
        requirement("numpy"),
        requirement("scipy"),
    ],
)

py_library(
    name = "hfss_runner",
    srcs = ["hfss_runner.py"],
    deps = [
        requirement("absl-py"),
        requirement("pyaedt"),
    ],
)

py_binary(
    name = "u_slot_patch_antenna_4l_optimizer_main",
    srcs = ["u_slot_patch_antenna_4l_optimizer_main.py"],
    deps = [
        ":constants",
        ":design_variable",
        ":hfss_optimizer",
        ":s_parameter_constraint",
        requirement("absl-py"),
    ],
)

py_binary(
    name = "u_slot_patch_antenna_6l_optimizer_main",
    srcs = ["u_slot_patch_antenna_6l_optimizer_main.py"],
    deps = [
        ":constants",
        ":design_variable",
        ":hfss_optimizer",
        ":s_parameter_constraint",
        requirement("absl-py"),
    ],
)

py_library(
    name = "s_parameter_constraint",
    srcs = ["s_parameter_constraint.py"],
    deps = [
        ":constraint",
        requirement("numpy"),
        requirement("pandas"),
    ],
)
