load("@pypi//:requirements.bzl", "requirement")

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "boost_odeint_example_main",
    srcs = ["boost_odeint_example_main.cc"],
    deps = [
        "//base",
        "@boost",
        "@eigen",
    ],
)

cc_binary(
    name = "eigen_example_main",
    srcs = ["eigen_example_main.cc"],
    deps = [
        "//base",
        "@eigen",
    ],
)

cc_binary(
    name = "mpc_example_main",
    srcs = ["mpc_example_main.cc"],
    deps = [
        "//base",
        "@eigen",
        "@libmpc",
    ],
)

py_binary(
    name = "multi_objective_optimizer_example_main",
    srcs = ["multi_objective_optimizer_example_main.py"],
    deps = [
        requirement("absl-py"),
        requirement("matplotlib"),
        requirement("pymoo"),
        requirement("SciencePlots"),
    ],
)

cc_binary(
    name = "opencv_gui_example_main",
    srcs = ["opencv_gui_example_main.cc"],
    deps = [
        "//base",
        "@opencv",
    ],
)

cc_binary(
    name = "opencv_3d_animation_example_main",
    srcs = ["opencv_3d_animation_example_main.cc"],
    deps = [
        "//base",
        "@opencv",
    ],
)
