load("@pypi//:requirements.bzl", "requirement")
load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_python//python:defs.bzl", "py_binary")

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "boost_odeint_example_main",
    srcs = ["boost_odeint_example_main.cc"],
    deps = [
        "//base",
        "@boost",
        "@eigen",
    ],
)

py_binary(
    name = "casadi_mpc_example_main",
    srcs = ["casadi_mpc_example_main.py"],
    deps = [
        "//utils/visualization:mpl_config",
        requirement("absl-py"),
        requirement("casadi"),
        requirement("numpy"),
        requirement("matplotlib"),
    ],
)

cc_binary(
    name = "eigen_example_main",
    srcs = ["eigen_example_main.cc"],
    deps = [
        "//base",
        "@eigen",
    ],
)

py_binary(
    name = "mopso_example_main",
    srcs = ["mopso_example_main.py"],
    deps = [
        "//utils/visualization:mpl_config",
        requirement("absl-py"),
        requirement("jmetalpy"),
        requirement("matplotlib"),
        requirement("numpy"),
    ],
)

cc_binary(
    name = "mpc_example_main",
    srcs = ["mpc_example_main.cc"],
    deps = [
        "//base",
        "@eigen",
        "@libmpc",
    ],
)

py_binary(
    name = "nsga2_example_main",
    srcs = ["nsga2_example_main.py"],
    deps = [
        "//utils/visualization:mpl_config",
        requirement("absl-py"),
        requirement("matplotlib"),
        requirement("pymoo"),
    ],
)

cc_binary(
    name = "opencv_gui_example_main",
    srcs = ["opencv_gui_example_main.cc"],
    deps = [
        "//base",
        "@opencv",
    ],
)

cc_binary(
    name = "opencv_3d_animation_example_main",
    srcs = ["opencv_3d_animation_example_main.cc"],
    deps = [
        "//base",
        "@opencv",
    ],
)
