step_time: 0.001
interceptor_swarm_configs {
  num_agents: 2
  agent_config {
    interceptor_type: HYDRA_70
    initial_state {
      position {
        x: 0
        y: 0
        z: 0
      }
      velocity {
        x: 1e-3
        y: 0
        z: 1e-3
      }
    }
    standard_deviation {
      position {
        x: 100
        y: 2000
        z: 0
      }
      velocity {
        x: 0
        y: 0
        z: 0
      }
    }
    dynamic_config {
      launch_config {
        launch_time: 0
      }
    }
    plotting_config {
      color: BLUE
      linestyle: DOTTED
      marker: TRIANGLE_UP
    }
    submunitions_config {
      num_submunitions: 7
      launch_config {
        launch_time: 2
      }
      agent_config {
        interceptor_type: MICROMISSILE
        dynamic_config {
          sensor_config {
            type: IDEAL
            frequency: 100
          }
        }
        plotting_config {
          color: BLUE
          linestyle: SOLID
          marker: TRIANGLE_DOWN
        }
      }
    }
  }
}
interceptor_swarm_configs {
  num_agents: 2
  agent_config {
    interceptor_type: HYDRA_70
    initial_state {
      position {
        x: 0
        y: 0
        z: 0
      }
      velocity {
        x: 1e-3
        y: 0
        z: 1e-3
      }
    }
    standard_deviation {
      position {
        x: 100
        y: 2000
        z: 0
      }
      velocity {
        x: 0
        y: 0
        z: 0
      }
    }
    dynamic_config {
      launch_config {
        launch_time: 10
      }
    }
    plotting_config {
      color: GREEN
      linestyle: DOTTED
      marker: TRIANGLE_UP
    }
    submunitions_config {
      num_submunitions: 7
      launch_config {
        launch_time: 2
      }
      agent_config {
        interceptor_type: MICROMISSILE
        dynamic_config {
          sensor_config {
            type: IDEAL
            frequency: 100
          }
        }
        plotting_config {
          color: GREEN
          linestyle: SOLID
          marker: TRIANGLE_DOWN
        }
      }
    }
  }
}
threat_swarm_configs {
  num_agents: 20
  agent_config {
    threat_type: DRONE
    initial_state {
      position {
        x: 8000
        y: 0
        z: 200
      }
      velocity {
        x: -40
        y: 0
        z: 0
      }
    }
    standard_deviation {
      position {
        x: 1000
        y: 1000
        z: 50
      }
      velocity {
        x: 20
        y: 50
        z: 0
      }
    }
    plotting_config {
      color: RED
      linestyle: SOLID
      marker: SQUARE
    }
  }
}
