load("@pypi//:requirements.bzl", "requirement")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "agglomerative_clusterer",
    srcs = ["agglomerative_clusterer.py"],
    deps = [
        ":clusterer",
        requirement("numpy"),
        requirement("scipy"),
    ],
)

py_test(
    name = "agglomerative_clusterer_test",
    srcs = ["agglomerative_clusterer_test.py"],
    deps = [
        ":agglomerative_clusterer",
        ":clusterer",
        requirement("absl-py"),
        requirement("numpy"),
    ],
)

py_library(
    name = "clusterer",
    srcs = ["clusterer.py"],
    deps = [requirement("numpy")],
)

py_test(
    name = "clusterer_test",
    srcs = ["clusterer_test.py"],
    deps = [
        ":clusterer",
        requirement("absl-py"),
        requirement("numpy"),
    ],
)

py_library(
    name = "k_means_clusterer",
    srcs = ["k_means_clusterer.py"],
    deps = [
        ":clusterer",
        requirement("numpy"),
        requirement("scipy"),
    ],
)

py_test(
    name = "k_means_clusterer_test",
    srcs = ["k_means_clusterer_test.py"],
    deps = [
        ":clusterer",
        ":k_means_clusterer",
        requirement("absl-py"),
        requirement("numpy"),
    ],
)

py_binary(
    name = "k_means_clusterer_main",
    srcs = ["k_means_clusterer_main.py"],
    deps = [
        ":clusterer",
        ":k_means_clusterer",
        requirement("absl-py"),
        requirement("matplotlib"),
        requirement("numpy"),
        requirement("SciencePlots"),
    ],
)

py_library(
    name = "min_cost_flow_clusterer",
    srcs = ["min_cost_flow_clusterer.py"],
    deps = [
        ":clusterer",
        requirement("numpy"),
        requirement("k-means-constrained"),
    ],
)

py_test(
    name = "min_cost_flow_clusterer_test",
    srcs = ["min_cost_flow_clusterer_test.py"],
    deps = [
        ":clusterer",
        ":min_cost_flow_clusterer",
        requirement("absl-py"),
        requirement("numpy"),
    ],
)

py_binary(
    name = "size_and_radius_constrained_clusterer_2d_main",
    srcs = ["size_and_radius_constrained_clusterer_2d_main.py"],
    deps = [
        ":agglomerative_clusterer",
        ":clusterer",
        ":k_means_clusterer",
        ":min_cost_flow_clusterer",
        requirement("absl-py"),
        requirement("matplotlib"),
        requirement("numpy"),
        requirement("SciencePlots"),
    ],
)

py_binary(
    name = "size_and_radius_constrained_clusterer_3d_main",
    srcs = ["size_and_radius_constrained_clusterer_3d_main.py"],
    deps = [
        ":agglomerative_clusterer",
        ":clusterer",
        ":k_means_clusterer",
        ":min_cost_flow_clusterer",
        requirement("absl-py"),
        requirement("matplotlib"),
        requirement("numpy"),
        requirement("SciencePlots"),
    ],
)
