load("@pypi//:requirements.bzl", "requirement")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "antenna",
    srcs = ["antenna.py"],
    deps = [
        ":radiation_pattern",
        requirement("numpy"),
    ],
)

py_binary(
    name = "antenna_single_reflection_path_main",
    srcs = ["antenna_single_reflection_path_main.py"],
    deps = [
        ":antenna",
        ":horn_antenna",
        ":patch_antenna",
        "//utils:constants",
        requirement("absl-py"),
        requirement("matplotlib"),
        requirement("numpy"),
        requirement("SciencePlots"),
    ],
)

py_library(
    name = "antenna_array",
    srcs = ["antenna_array.py"],
    deps = [
        ":antenna",
        ":antenna_factory",
        ":isotropic_antenna",
        ":radiation_pattern",
        "//simulation/antenna/proto:antenna_array_config_py_proto",
        "//utils:coordinates",
        "//utils:quaternion",
        requirement("numpy"),
    ],
)

py_binary(
    name = "antenna_array_main",
    srcs = ["antenna_array_main.py"],
    data = ["//simulation/antenna/configs"],
    deps = [
        ":antenna_array",
        "//simulation/antenna/proto:antenna_array_config_py_proto",
        requirement("absl-py"),
        requirement("matplotlib"),
        requirement("numpy"),
        requirement("protobuf"),
        requirement("SciencePlots"),
    ],
)

py_test(
    name = "antenna_array_test",
    srcs = ["antenna_array_test.py"],
    deps = [
        ":antenna_array",
        "//utils:quaternion",
        requirement("absl-py"),
        requirement("numpy"),
    ],
)

py_binary(
    name = "antenna_array_characterization_main",
    srcs = ["antenna_array_characterization_main.py"],
    data = ["//simulation/antenna/configs"],
    deps = [
        ":antenna_array",
        "//simulation/antenna/proto:antenna_array_config_py_proto",
        "//utils/visualization:color_maps",
        requirement("absl-py"),
        requirement("matplotlib"),
        requirement("numpy"),
        requirement("protobuf"),
        requirement("SciencePlots"),
    ],
)

py_binary(
    name = "antenna_array_optimal_front_main",
    srcs = ["antenna_array_optimal_front_main.py"],
    data = ["//simulation/antenna/data:antenna_array_optimal_front_data"],
    deps = [
        requirement("absl-py"),
        requirement("matplotlib"),
        requirement("pandas"),
        requirement("SciencePlots"),
    ],
)

py_binary(
    name = "antenna_array_radiation_pattern_main",
    srcs = ["antenna_array_radiation_pattern_main.py"],
    data = ["//simulation/antenna/configs"],
    deps = [
        ":antenna_array",
        "//simulation/antenna/proto:antenna_array_config_py_proto",
        "//utils:coordinates",
        "//utils/visualization:animator",
        "//utils/visualization:color_maps",
        requirement("absl-py"),
        requirement("matplotlib"),
        requirement("numpy"),
        requirement("protobuf"),
        requirement("SciencePlots"),
    ],
)

py_binary(
    name = "antenna_array_radiation_pattern_comparison_main",
    srcs = ["antenna_array_radiation_pattern_comparison_main.py"],
    data = ["//simulation/antenna/configs"],
    deps = [
        ":antenna_array",
        "//simulation/antenna/proto:antenna_array_config_py_proto",
        "//utils:constants",
        "//utils/visualization:animator",
        requirement("absl-py"),
        requirement("matplotlib"),
        requirement("numpy"),
        requirement("protobuf"),
        requirement("SciencePlots"),
    ],
)

py_library(
    name = "antenna_array_optimization",
    srcs = ["antenna_array_optimization.py"],
    deps = [
        ":antenna_array",
        "//simulation/antenna/proto:antenna_array_config_py_proto",
        "//simulation/antenna/proto:geometry_py_proto",
        "//utils/optimization:problem",
        requirement("numpy"),
    ],
)

py_binary(
    name = "antenna_array_1d_aperture_optimization_main",
    srcs = ["antenna_array_1d_aperture_optimization_main.py"],
    data = ["//simulation/antenna/configs"],
    deps = [
        ":antenna_array_optimization",
        "//simulation/antenna/proto:antenna_array_config_py_proto",
        "//utils/optimization:nsga2_multi_objective_optimizer",
        requirement("absl-py"),
        requirement("matplotlib"),
        requirement("numpy"),
        requirement("protobuf"),
        requirement("pymoo"),
        requirement("SciencePlots"),
    ],
)

py_binary(
    name = "antenna_array_1d_line_optimization_main",
    srcs = ["antenna_array_1d_line_optimization_main.py"],
    data = ["//simulation/antenna/configs"],
    deps = [
        ":antenna_array_optimization",
        "//simulation/antenna/proto:antenna_array_config_py_proto",
        "//utils/optimization:nsga2_multi_objective_optimizer",
        requirement("absl-py"),
        requirement("matplotlib"),
        requirement("numpy"),
        requirement("protobuf"),
        requirement("pymoo"),
        requirement("SciencePlots"),
    ],
)

py_binary(
    name = "antenna_array_2d_surface_optimization_main",
    srcs = ["antenna_array_2d_surface_optimization_main.py"],
    data = ["//simulation/antenna/configs"],
    deps = [
        ":antenna_array_optimization",
        "//simulation/antenna/proto:antenna_array_config_py_proto",
        "//utils/optimization:nsga2_multi_objective_optimizer",
        requirement("absl-py"),
        requirement("matplotlib"),
        requirement("numpy"),
        requirement("protobuf"),
        requirement("pymoo"),
        requirement("SciencePlots"),
    ],
)

py_library(
    name = "antenna_array_spectrum",
    srcs = ["antenna_array_spectrum.py"],
    deps = [
        ":antenna_array",
        requirement("numpy"),
    ],
)

py_library(
    name = "antenna_array_1d_spectrum",
    srcs = ["antenna_array_1d_spectrum.py"],
    deps = [
        ":antenna_array",
        ":antenna_array_spectrum",
        requirement("numpy"),
    ],
)

py_binary(
    name = "antenna_array_1d_spectrum_main",
    srcs = ["antenna_array_1d_spectrum_main.py"],
    data = ["//simulation/antenna/configs"],
    deps = [
        ":antenna_array",
        ":antenna_array_1d_spectrum",
        "//simulation/antenna/proto:antenna_array_config_py_proto",
        "//utils:constants",
        requirement("absl-py"),
        requirement("matplotlib"),
        requirement("numpy"),
        requirement("protobuf"),
        requirement("SciencePlots"),
    ],
)

py_library(
    name = "antenna_factory",
    srcs = ["antenna_factory.py"],
    data = ["//simulation/antenna/data:antenna_radiation_pattern_data"],
    deps = [
        ":antenna",
        ":antenna_radiation_pattern",
        ":dipole_antenna",
        ":horn_antenna",
        ":isotropic_antenna",
        ":patch_antenna",
        "//simulation/antenna/proto:antenna_config_py_proto",
    ],
)

py_test(
    name = "antenna_factory_test",
    srcs = ["antenna_factory_test.py"],
    data = ["//simulation/antenna/data:antenna_radiation_pattern_data"],
    deps = [
        ":antenna_factory",
        ":antenna_radiation_pattern",
        ":dipole_antenna",
        ":horn_antenna",
        ":isotropic_antenna",
        ":patch_antenna",
        "//simulation/antenna/proto:antenna_config_py_proto",
        requirement("absl-py"),
        requirement("numpy"),
    ],
)

py_library(
    name = "antenna_radiation_pattern",
    srcs = ["antenna_radiation_pattern.py"],
    deps = [
        ":antenna",
        ":radiation_pattern",
        "//utils:constants",
        "//utils:coordinates",
        requirement("numpy"),
        requirement("pandas"),
        requirement("scipy"),
    ],
)

py_binary(
    name = "antenna_radiation_pattern_main",
    srcs = ["antenna_radiation_pattern_main.py"],
    data = ["//simulation/antenna/data:antenna_radiation_pattern_data"],
    deps = [
        ":antenna_radiation_pattern",
        "//utils:constants",
        "//utils:coordinates",
        "//utils/visualization:color_maps",
        requirement("absl-py"),
        requirement("matplotlib"),
        requirement("numpy"),
        requirement("SciencePlots"),
    ],
)

py_library(
    name = "dipole_antenna",
    srcs = ["dipole_antenna.py"],
    deps = [
        ":antenna",
        ":radiation_pattern",
        requirement("numpy"),
        requirement("scipy"),
    ],
)

py_binary(
    name = "dipole_antenna_main",
    srcs = ["dipole_antenna_main.py"],
    deps = [
        ":dipole_antenna",
        "//utils:coordinates",
        "//utils/visualization:color_maps",
        requirement("absl-py"),
        requirement("matplotlib"),
        requirement("numpy"),
        requirement("SciencePlots"),
    ],
)

py_library(
    name = "horn_antenna",
    srcs = ["horn_antenna.py"],
    deps = [
        ":antenna",
        ":radiation_pattern",
        "//utils:coordinates",
        requirement("numpy"),
        requirement("scipy"),
    ],
)

py_binary(
    name = "horn_antenna_main",
    srcs = ["horn_antenna_main.py"],
    deps = [
        ":horn_antenna",
        "//utils:coordinates",
        "//utils/visualization:color_maps",
        requirement("absl-py"),
        requirement("matplotlib"),
        requirement("numpy"),
        requirement("SciencePlots"),
    ],
)

py_library(
    name = "isotropic_antenna",
    srcs = ["isotropic_antenna.py"],
    deps = [
        ":antenna",
        ":radiation_pattern",
        requirement("numpy"),
    ],
)

py_library(
    name = "patch_antenna",
    srcs = ["patch_antenna.py"],
    deps = [
        ":antenna",
        ":radiation_pattern",
        "//utils:coordinates",
        requirement("numpy"),
    ],
)

py_binary(
    name = "patch_antenna_main",
    srcs = ["patch_antenna_main.py"],
    deps = [
        ":patch_antenna",
        "//utils:coordinates",
        "//utils/visualization:color_maps",
        requirement("absl-py"),
        requirement("matplotlib"),
        requirement("numpy"),
        requirement("SciencePlots"),
    ],
)

py_binary(
    name = "patch_antenna_design_main",
    srcs = ["patch_antenna_design_main.py"],
    deps = [
        requirement("absl-py"),
        requirement("numpy"),
    ],
)

py_library(
    name = "radiation_pattern",
    srcs = ["radiation_pattern.py"],
    deps = [
        "//utils:constants",
        requirement("numpy"),
    ],
)

py_test(
    name = "radiation_pattern_test",
    srcs = ["radiation_pattern_test.py"],
    deps = [
        ":radiation_pattern",
        requirement("absl-py"),
        requirement("numpy"),
    ],
)
