name: "Hydra 70"
agent_type: CARRIER_INTERCEPTOR
cost: 30000
acceleration_config {
  max_forward_acceleration: 0
  max_reference_normal_acceleration: 300
  reference_speed: 1000
}
boost_config {
  boost_time: 1
  boost_acceleration: 100
}
lift_drag_config {
  lift_coefficient: 0.2
  drag_coefficient: 1
  lift_drag_ratio: 5
}
body_config {
  mass: 15.8
  cross_sectional_area: 0.004
  fin_area: 0.007
  body_area: 0.12
}
visualization_config {
  symbol_present: "friendly_missile_interceptor_lr_present"
  symbol_destroyed: "friendly_missile_interceptor_lr_destroyed"
}
