name: "Micromissile"
agent_type: MISSILE_INTERCEPTOR
cost: 2000
acceleration_config {
  max_forward_acceleration: 0
  max_reference_normal_acceleration: 300
  reference_speed: 1000
}
boost_config {
  boost_time: 0.3
  boost_acceleration: 350
}
lift_drag_config {
  lift_coefficient: 0.2
  drag_coefficient: 0.7
  lift_drag_ratio: 5
}
body_config {
  mass: 0.37
  cross_sectional_area: 0.0003
  fin_area: 0.0006
  body_area: 0.01
}
visualization_config {
  symbol_present: "friendly_missile_interceptor_sr_present"
  symbol_destroyed: "friendly_missile_interceptor_sr_destroyed"
}
