name: "Quadcopter"
agent_type: ROTARY_WING_THREAT
cost: 1000
acceleration_config {
  max_forward_acceleration: 50
  max_reference_normal_acceleration: 300
  reference_speed: 1000
}
lift_drag_config {
  lift_drag_ratio: 5
}
body_config {
  mass: 1
}
hit_config {
  hit_radius: 1
  kill_probability: 0.9
}
power_table {
  power: IDLE
  speed: 0
}
power_table {
  power: LOW
  speed: 20
}
power_table {
  power: CRUISE
  speed: 40
}
power_table {
  power: MIL
  speed: 50
}
power_table {
  power: MAX
  speed: 75
}
visualization_config {
  symbol_present: "hostile_ua_present"
  symbol_destroyed: "hostile_ua_destroyed"
}
